### ISSUE TITLE
Strings garbled (sybase api version: CS_VERSION_125 )

### ISSUE THREAD

**Issue by Eggache666** [vimsh/db_conn#2]
When i fetch a little amount of data, the strings returned are correct. But when the volume of records increases, most of the data(datatype CS_CHAR_TYPE) behind is incorrect: correct string followed by garbled.

I'm not familiar with Sybase APIs, and made some changes in sybase_driver.hpp.

1, below the function 'ct_describe' about line 620, I add this:
if (columns[i].datatype == CS_CHAR_TYPE)  { columns[i].format = CS_FMT_PADNULL; }

2, comments 2 lines at line 196:
//if (CS_ROW_FAIL == retcode)
//    throw std::runtime_error(std::string(__FUNCTION__).append(": Error fetching row ").append(std::to_string(result)));

3, In function "void process_result(bool compute, bool bind)" about line 645, add 3 lines:
if (columns[i].datatype == CS_CHAR_TYPE)
	columndata[i].allocate(columns[i].maxlength + 2);
else
	columndata[i].allocate(columns[i].maxlength);

4, Commented on the associated exception about line 710

After 4 steps, it works in debug mode(crashed in release mode), but still throw exceptions in callback functions, so i comment cs_msg_callback, ct_msg_callback and srv_msg_callback in the constructor of driver. 

While this can get the right results, I'm not sure it's the right approach, and are there other better ways to fix it?

Thank you!

**Comment by vimsh** [comment]
I currently don't have a sybase around. Can you email me?

**Comment by vimsh** [comment]
i'll commit these changes:

in void allocate(const size_t size) change body to have these 2 line:
data.resize(size);
std::memset(data.data(), 0, size);

in virtual std::string get_string(size_t col_idx) change return line to:
return std::move(std::string((char*)columndata[col_idx], 0, columndata[col_idx].data.size()));

in virtual std::u16string get_u16string(size_t col_idx) change return line to:
return std::move(std::u16string(reinterpret_cast<char16_t*>((char*)columndata[col_idx]), 0, columndata[col_idx].data.size() / sizeof(char16_t)));

**Comment by Eggache666** [comment]
Thank you for your reply!
I recovered all previous changes and then changed two places:

in virtual std::string get_string(size_t col_idx) change return line to:
return std::move(std::string((char*)columndata[col_idx], 0, columndata[col_idx].data.size()));
in virtual std::u16string get_u16string(size_t col_idx) change return line to:
return std::move(std::u16string(reinterpret_cast<char16_t*>((char*)columndata[col_idx]), 0, columndata[col_idx].data.size() / sizeof(char16_t)));

below the function 'ct_describe' about line 620,  add this:
if (columns[i].datatype == CS_CHAR_TYPE) { columns[i].format = CS_FMT_PADNULL; }

After that, the return result is correct

**Comment by vimsh** [comment]
I would rather have the changes as I had described - in 3 places.
According to Sybase API pad null should be done on fixed length strings and binary formats. There is no specs on how variable length strings are handled. Since memset is very fast,  I think resetting the buffer to 0 all the time in allocate function is a safer bet than setting format to pad null. If you prefer setting format then you should do it as recommended by API for all fixed length strings and binary data types.
 
Sent from BlueMail On May 27, 2018, at 5:38 AM, Eggache666 <notifications@github.com> wrote:

Thank you for your reply!
 I recovered all previous changes and then changed two places:

in virtual std::string get_string(size_t col_idx) change return line to:
 return std::move(std::string((char*)columndata[col_idx], 0, columndata[col_idx].data.size()));
 in virtual std::u16string get_u16string(size_t col_idx) change return line to:
 return std::move(std::u16string(reinterpret_cast<char16_t*>((char*)columndata[col_idx]), 0, columndata[col_idx].data.size() / sizeof(char16_t)));

below the function 'ct_describe' about line 620, add this:
 if (columns[i].datatype == CS_CHAR_TYPE) { columns[i].format = CS_FMT_PADNULL; }

After that, the return result is correct
